#FOR DEVELOPMENT OF PREPROCESSOR ONLY - PRODUCTION BUILD DONE SEPARATELY
#FOR DEVELOPMENT OF PREPROCESSOR ONLY - PRODUCTION BUILD DONE SEPARATELY
#FOR DEVELOPMENT OF PREPROCESSOR ONLY - PRODUCTION BUILD DONE SEPARATELY


version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.devui  # Updated to Dockerfile.devui for frontend
      platforms: 
        - linux/amd64  # Force x64 build
    volumes:
      - .:/app  # Mount the entire root directory
      - /app/node_modules  # Prevent overwriting of node_modules
    ports:
      - "8080:8080"  # Port for Vue.js (default for yarn dev)
    environment:
      - CHOKIDAR_USEPOLLING=true  # Ensures file changes are detected in container      
    command: npm run serve-ui
    networks:
      - webnet

  backend:
    build:
      context: .
      dockerfile: Dockerfile.devapi  # Updated to Dockerfile.devapi for backend
      platforms: 
        - linux/amd64  # Force x64 build
    volumes:
      - .:/app  # Mount the entire root directory
    ports:
      - "5005:5000"  # Flask API will be served on this port
    networks:
      - webnet
    environment:
      - FLASK_ENV=development  # Enables auto-reloading in Flask
      - FLASK_DEBUG=1  # Explicitly enable debug mode      
      - PYTHONUNBUFFERED=1  # Disable Python output buffering

networks:
  webnet:
    driver: bridge
